apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: cloudnative
    type: cost-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tobiwilly/cloud-native-backend:1.0
        ports:
        - containerPort: 5000

